# Generated by Django 4.2.4 on 2023-08-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langchain_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='files',
            field=models.FileField(max_length=200, upload_to='uploads'),
        ),
    ]
